### ISSUE TITLE
Clarify DockerScriptRunner docs

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-scripts#128]
### Issue description

![image](https://github.com/kestra-io/plugin-scripts/assets/86264395/7d081839-37e2-4410-9b72-7a30a5bb9b9e)

When is this an issue? worth clarifying a bit more + adding 1-2 examples - @loicmathieu you can ping me to discuss if needed

**Comment by loicmathieu** [comment]
After we merge all pending runners, I'll have a look to align the doc and maybe provide example.
I'll ping you when I have something so you can have a look before I merge the changes.

**Comment by loicmathieu** [comment]
The documentation has been updated.
