### ISSUE TITLE
Unable to load all plugin classes from from 'xxx/plugin-script-python-0.19.0.jar'. Cause: [NoClassDefFoundError] io/kestra/core/tasks/scripts/AbstractBash

### ISSUE THREAD

**Issue by zhaosirlaile** [kestra-io/plugin-scripts#184]
### Describe the issue

Why can't I load this plugin (plugin-script-python-0.19.0.jar)?

![image](https://github.com/user-attachments/assets/f4bb74fe-60a2-4c0d-b558-1a554b9ae79d)

### Environment

- Kestra Version: v0.19.0
- [plugin-scripts](https://github.com/kestra-io/plugin-scripts): v0.19.0

**Comment by Ben8t** [comment]
Hello @zhaosirlaile , can you give us more context on your Kestra installation, and what are you trying to do please?

**Comment by zhaosirlaile** [comment]
Hello @Ben8t  , I seem to have found the cause of the problem. It should be related to packaging (caused by not using shadowJar for packaging). Now it is normal. Thank you 🙏.

**Comment by Ben8t** [comment]
Ok thanks ! Closing
