### ISSUE TITLE
[UI] Remove the interpreter and runner warning in the code editor

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-scripts#80]
### Feature description

Reported by the community:

![image](https://github.com/kestra-io/plugin-scripts/assets/86264395/8b6a0db5-c96d-448b-852d-a31b623f1474)

The runner and interpreter should use the default values without raising a warning:

![image](https://github.com/kestra-io/plugin-scripts/assets/86264395/ae8a3d1c-3f8d-4d5b-8d4a-592f23e55819)

**Comment by tchiotludo** [comment]
duplicate [this](https://github.com/kestra-io/kestra/issues/2175)

**Comment by anna-geller** [comment]
wow, that other issue title is so abstract, I'll extend that other issue title
